package net.lab.util;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;

public class Pdf {
	public static String FILE = "c:/FirstPdf.pdf";
	private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,Font.BOLD);
	
	public Pdf() {
		Document Doc = new Document();
		try {
			PdfWriter.getInstance(Doc, new FileOutputStream(FILE));
			Doc.open();
			addMetaData(Doc);
			addTitlePage(Doc);
			Doc.close();
		} catch (FileNotFoundException | DocumentException e) {
			e.printStackTrace();
		}
		
	}
	
	
	 private static void addMetaData(Document document) {
		    document.addTitle("My first PDF נואכüםמ");
		    document.addSubject("Using iText");
		    document.addKeywords("Java, PDF, iText");
		    document.addAuthor("LAB");
		    document.addCreator("LAB");
		  }

	 private static void addTitlePage(Document document)
		      throws DocumentException {
		    Paragraph preface = new Paragraph();
		    // We add one empty line
		    addEmptyLine(preface, 1);
		    // Lets write a big header
		    preface.add(new Paragraph("Title of the document", catFont));

		    addEmptyLine(preface, 1);
		    // Will create: Report generated by: _name, _date
		    preface.add(new Paragraph("Report generated by מע: " + System.getProperty("user.name") + ", " + new Date(),catFont));
		    addEmptyLine(preface, 3);
		    preface.add(new Paragraph(" ממעעע",catFont));
		    addEmptyLine(preface, 8);
		    document.add(preface);
		    
		    
		    Anchor anchor = new Anchor("First Chapter", catFont);
		    anchor.setName("First Chapter");
		    Chapter catPart = new Chapter(new Paragraph(anchor), 1);
		    
		    Paragraph subPara = new Paragraph("Subcategory 2", catFont);
		    Section subCatPart = catPart.addSection(subPara);
		    createTable(subCatPart);
		    document.add(subCatPart);
		    
		    // Start a new page
		    document.newPage();
		  }	 
	 
	 private static void addEmptyLine(Paragraph paragraph, int number) {
		    for (int i = 0; i < number; i++) {
		      paragraph.add(new Paragraph(" "));
		    }
		  }
	 
	 
	 private static void createTable(Section subCatPart)
		      throws BadElementException {
		    PdfPTable table = new PdfPTable(3);

		    PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
		    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		    table.addCell(c1);

		    c1 = new PdfPCell(new Phrase("Table Header 2"));
		    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		    table.addCell(c1);

		    c1 = new PdfPCell(new Phrase("Table Header 3"));
		    c1.setHorizontalAlignment(Element.ALIGN_CENTER);
		    table.addCell(c1);
		    table.setHeaderRows(1);

		    table.addCell("1.0");
		    table.addCell("1.1");
		    table.addCell("1.2");
		    table.addCell("2.1");
		    table.addCell("2.2");
		    table.addCell("2.3");

		    subCatPart.add(table);

		  }
	 
}
